export const MOVIES_LOAD = 'MOVIES_LOAD';
export const MOVIE_FINDING = 'MOVIE_FINDING';
export const MENU_VISIBLE_CHANGE = 'MENU_VISIBLE_CHANGE';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
export const ERROR_DISPLAY_ON = 'ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF = 'ERROR_DISPLAY_OFF';
